### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by jonshouse1** [Pakequis/Raspberry-pi-TV-sim#1]
It may be possible to remove both the relay and the Arduino

This describes how to crudely read a POT using PWM, 2 resistors and a capacitor
https://www.circuitbasics.com/using-potentiometers-with-raspberry-pi/

You could remove the relay board and play the "TV static" as a video clip.

Using fork() you may be able to start one clip playing before the previous has finished, that might cure the framebuffer showing issue.
or failing that try adding something like "cp /dev/zero /dev/fb0" to blank the framebuffer.

**Comment by Pakequis** [comment]
Yes, there are ADC readout options, but I had some Arduino Mini Pros and I have to use them.

Static through a video clip is also on my radar. I will test new options when I get back to this project.

Thank you for the tips.
